name: Server Continuous Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          file: ./Dockerfile.prod
          tags: |
            ghcr.io/ootmm/multi-server:latest
            ghcr.io/ootmm/multi-server:${{ github.sha }}
